# datakit/ai_assistant/context/context_manager.py

"""
Context manager for DataKit AI Assistant.

Manages:

- Dataset context generated by DatasetContextBuilder
- Data-quality problems detected by preprocessing detectors
- Preprocessing history
- Conversion of the context to JSON/Markdown for the LLM
"""

import json
import logging
from typing import Optional, Dict, Any

import pandas as pd


logger = logging.getLogger(__name__)


class ContextManager:
    """Manages dataset and preprocessing context for the AI assistant."""

    def __init__(self, dataset_builder, preprocessing_context):
        self.dataset_builder = dataset_builder
        self.preprocessing_context = preprocessing_context

        self.dataset_context: Optional[Dict[str, Any]] = None
        self.current_dataset_name: Optional[str] = None

    # =============================================================
    # Dataset
    # =============================================================

    def update_dataset(
        self,
        dataframe: pd.DataFrame,
        dataset_name: str = "dataset"
    ) -> None:
        """
        Generate and store the dataset context.

        DatasetContextBuilder runs the tabular detectors and
        generates the complete dataset-quality context.
        """

        if dataframe is None or dataframe.empty:
            self.dataset_context = None
            self.current_dataset_name = None

            logger.info("Dataset context cleared")
            return

        self.dataset_context = self.dataset_builder.build(
            dataframe,
            dataset_name
        )

        self.current_dataset_name = dataset_name

        logger.info(
            f"Dataset context updated: "
            f"{dataset_name} ({len(dataframe)} rows)"
        )

    # =============================================================
    # Preprocessing
    # =============================================================

    def update_preprocessing(
        self,
        operation_name: str,
        columns: list,
        parameters: dict = None
    ) -> None:
        """
        Add a preprocessing operation to the context.
        """

        self.preprocessing_context.add_operation(
            operation_name,
            columns,
            parameters
        )

        logger.debug(
            f"Preprocessing operation added: {operation_name}"
        )

    # =============================================================
    # Full context
    # =============================================================

    def get_full_context(self) -> Dict[str, Any]:
        """
        Return the complete AI context.

        Contains:
        - Dataset information
        - Detector results
        - Preprocessing history
        """

        return {
            "dataset": self.dataset_context,
            "preprocessing": self.preprocessing_context.get_context()
        }

    # =============================================================
    # JSON format
    # =============================================================

    def to_prompt_format(self) -> str:
        """
        Convert the complete context to JSON text.

        This format can be directly inserted into an LLM prompt.
        """

        context = self.get_full_context()

        return json.dumps(
            context,
            indent=2,
            ensure_ascii=False,
            default=str
        )

    # =============================================================
    # Markdown format
    # =============================================================

    def to_markdown_context(self) -> str:
        """
        Convert the context into a compact Markdown representation
        optimized for LLM readability.
        """

        if not self.dataset_context:
            return "Aucune donnée chargée."

        lines = []

        # =========================================================
        # Dataset overview
        # =========================================================

        dataset_name = self.dataset_context.get(
            "dataset_name",
            "unknown"
        )

        shape = self.dataset_context.get(
            "shape",
            {}
        )

        lines.append(
            f"## 📊 Dataset: {dataset_name}"
        )

        lines.append("")

        lines.append(
            f"- **Lignes:** {shape.get('rows', 0)}"
        )

        lines.append(
            f"- **Colonnes:** {shape.get('columns', 0)}"
        )

        # =========================================================
        # Detected problems
        # =========================================================

        lines.append("")
        lines.append("## 🚨 Problèmes détectés")

        detected_problems = self.dataset_context.get(
            "detected_problems",
            []
        )

        if detected_problems:

            for problem in detected_problems:

                detector = problem.get(
                    "detector",
                    "unknown"
                )

                column = problem.get(
                    "column"
                )

                description = problem.get(
                    "description",
                    "Problème détecté"
                )

                if column:
                    lines.append(
                        f"- **{detector}** — "
                        f"`{column}` : {description}"
                    )
                else:
                    lines.append(
                        f"- **{detector}** : "
                        f"{description}"
                    )

        else:
            lines.append(
                "- Aucun problème détecté."
            )

        # =========================================================
        # Detector results
        # =========================================================

        detectors = self.dataset_context.get(
            "detectors",
            {}
        )

        # =========================================================
        # Missing values
        # =========================================================

        missing = detectors.get(
            "missing_values",
            {}
        )

        lines.append("")
        lines.append("### 🔍 Valeurs manquantes")

        total_missing = missing.get(
            "total_missing",
            0
        )

        missing_percentage = missing.get(
            "missing_percentage",
            0
        )

        lines.append(
            f"- **Total:** {total_missing}"
        )

        lines.append(
            f"- **Pourcentage global:** "
            f"{missing_percentage:.2f}%"
        )

        missing_columns = missing.get(
            "columns",
            {}
        )

        if missing_columns:

            for column, stats in missing_columns.items():

                count = stats.get(
                    "missing_count",
                    0
                )

                percentage = stats.get(
                    "missing_percentage",
                    0
                )

                if count > 0:
                    lines.append(
                        f"- `{column}` : "
                        f"{count} valeur(s) manquante(s) "
                        f"({percentage:.1f}%)"
                    )

        # =========================================================
        # Outliers
        # =========================================================

        outliers = detectors.get(
            "outliers",
            {}
        )

        lines.append("")
        lines.append("### 📈 Outliers")

        lines.append(
            f"- **Méthode:** "
            f"{outliers.get('method', 'unknown')}"
        )

        lines.append(
            f"- **Seuil:** "
            f"{outliers.get('threshold', 'N/A')}"
        )

        outlier_columns = outliers.get(
            "columns",
            {}
        )

        outlier_found = False

        for column, stats in outlier_columns.items():

            count = stats.get(
                "n_outliers",
                0
            )

            percentage = stats.get(
                "percentage",
                0
            )

            if count > 0:

                outlier_found = True

                lines.append(
                    f"- `{column}` : "
                    f"{count} outlier(s) "
                    f"({percentage:.1f}%)"
                )

        if not outlier_found:
            lines.append(
                "- Aucun outlier détecté."
            )

        # =========================================================
        # Correlations
        # =========================================================

        correlation = detectors.get(
            "correlation",
            {}
        )

        lines.append("")
        lines.append("### 🔗 Corrélations")

        lines.append(
            f"- **Seuil:** "
            f"{correlation.get('threshold', 'N/A')}"
        )

        high_corr = correlation.get(
            "high_correlation_pairs",
            []
        )

        if high_corr:

            for pair in high_corr:

                col1 = pair.get(
                    "col1",
                    "unknown"
                )

                col2 = pair.get(
                    "col2",
                    "unknown"
                )

                value = pair.get(
                    "correlation",
                    0
                )

                lines.append(
                    f"- `{col1}` ↔ `{col2}` : "
                    f"{value:.2f}"
                )

        else:
            lines.append(
                "- Aucune forte corrélation détectée."
            )

        # =========================================================
        # Cardinality
        # =========================================================

        cardinality = detectors.get(
            "cardinality",
            {}
        )

        lines.append("")
        lines.append("### 🔢 Cardinalité")

        lines.append(
            f"- **Maximum recommandé:** "
            f"{cardinality.get('max_categories', 'N/A')}"
        )

        cardinality_columns = cardinality.get(
            "columns",
            {}
        )

        if cardinality_columns:

            for column, count in cardinality_columns.items():

                lines.append(
                    f"- `{column}` : "
                    f"{count} catégories"
                )

        else:
            lines.append(
                "- Aucune colonne catégorielle problématique."
            )

        # =========================================================
        # Duplicates
        # =========================================================

        duplicates = detectors.get(
            "duplicates",
            {}
        )

        duplicate_count = duplicates.get(
            "duplicate_count",
            0
        )

        lines.append("")
        lines.append("### 📋 Doublons")

        lines.append(
            f"- **Lignes dupliquées:** "
            f"{duplicate_count}"
        )

        # =========================================================
        # Preprocessing history
        # =========================================================

        preprocessing = (
            self.preprocessing_context.get_context()
        )

        lines.append("")
        lines.append("## 🔧 Opérations de prétraitement")

        operations = preprocessing.get(
            "operations",
            []
        )

        if operations:

            for operation in operations:

                operation_name = operation.get(
                    "operation",
                    "unknown"
                )

                columns = operation.get(
                    "columns",
                    []
                )

                parameters = operation.get(
                    "parameters",
                    {}
                )

                if columns:

                    columns_str = ", ".join(
                        columns
                    )

                    lines.append(
                        f"- **{operation_name}** "
                        f"sur: {columns_str}"
                    )

                else:

                    lines.append(
                        f"- **{operation_name}**"
                    )

                if parameters:

                    lines.append(
                        f"  - Paramètres: "
                        f"{parameters}"
                    )

        else:

            lines.append(
                "- Aucune opération effectuée pour l'instant."
            )

        # =========================================================
        # Return final context
        # =========================================================

        return "\n".join(lines)